name: tf-docs ci

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v5

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - name: go-task/setup-task
        uses: go-task/setup-task@v2.0.0

      - name: setup
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ../plenary.nvim
          git clone --depth 1 https://github.com/nvim-telescope/telescope.nvim ../telescope.nvim
          git clone --depth 1 https://github.com/ibhagwan/fzf-lua ../fzf-lua
          git clone --depth 1 https://github.com/folke/snacks.nvim ../snacks.nvim

      - name: run tests
        run: |
          nvim --version
          task test
